name = "couple-date"
compatibility_date = "2026-01-01"
pages_build_output_dir = "."

[[d1_databases]]
binding = "DB"
database_name = "couple_date_db"
database_id = "66d4cb96-6af8-4bea-a8a9-6681a8449d62"
